"""empty message

Revision ID: 2209ea9dd941
Revises: 4a95a0bb1a69
Create Date: 2019-08-19 20:48:19.696248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2209ea9dd941'
down_revision = '4a95a0bb1a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_daytime', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_daytime', 'date')
    # ### end Alembic commands ###
