"""empty message

Revision ID: 3301abee3cb0
Revises: d16ba7bf581e
Create Date: 2019-08-22 12:10:24.709765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3301abee3cb0'
down_revision = 'd16ba7bf581e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer_users', sa.Column('update_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer_users', 'update_time')
    # ### end Alembic commands ###
