"""empty message

Revision ID: 4a95a0bb1a69
Revises: 7a2c936cbbb9
Create Date: 2019-08-19 17:20:54.423808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a95a0bb1a69'
down_revision = '7a2c936cbbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'timer_users', ['user_name'])
    op.create_unique_constraint(None, 'timer_users', ['account'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timer_users', type_='unique')
    op.drop_constraint(None, 'timer_users', type_='unique')
    # ### end Alembic commands ###
