"""empty message

Revision ID: 7b8980541657
Revises: db428eb7b834
Create Date: 2019-08-22 16:21:02.310947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b8980541657'
down_revision = 'db428eb7b834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer_times', 'update_time')
    op.add_column('timer_users', sa.Column('update_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer_users', 'update_time')
    op.add_column('timer_times', sa.Column('update_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
