"""empty message

Revision ID: 9b50f24bdc62
Revises: 7b8980541657
Create Date: 2019-08-23 16:38:32.484260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b50f24bdc62'
down_revision = '7b8980541657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'record_mac', ['mac'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record_mac', type_='unique')
    # ### end Alembic commands ###
