"""empty message

Revision ID: aee04dd70270
Revises: c80b259bd409
Create Date: 2019-08-19 16:50:44.431902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee04dd70270'
down_revision = 'c80b259bd409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer_users', sa.Column('type', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer_users', 'type')
    # ### end Alembic commands ###
