"""empty message

Revision ID: c42e40c2a2f6
Revises: 9b50f24bdc62
Create Date: 2019-08-29 13:27:33.655611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42e40c2a2f6'
down_revision = '9b50f24bdc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_mac', sa.Column('type', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_mac', 'type')
    # ### end Alembic commands ###
