"""empty message

Revision ID: c80b259bd409
Revises: fb49f49d95b6
Create Date: 2019-08-19 16:36:26.179584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80b259bd409'
down_revision = 'fb49f49d95b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_daytime',
    sa.Column('daytime_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_point', sa.VARCHAR(length=2), nullable=True),
    sa.Column('time_count', sa.VARCHAR(length=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['timer_users.user_id'], ),
    sa.PrimaryKeyConstraint('daytime_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_daytime')
    # ### end Alembic commands ###
