"""empty message

Revision ID: d16ba7bf581e
Revises: c7fb17555d42
Create Date: 2019-08-19 21:24:56.511472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16ba7bf581e'
down_revision = 'c7fb17555d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_daytime', sa.Column('time_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record_daytime', 'time_date')
    # ### end Alembic commands ###
