"""empty message

Revision ID: db428eb7b834
Revises: 3301abee3cb0
Create Date: 2019-08-22 16:20:22.482082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db428eb7b834'
down_revision = '3301abee3cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer_times', sa.Column('update_time', sa.Integer(), nullable=True))
    op.drop_column('timer_users', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer_users', sa.Column('update_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('timer_times', 'update_time')
    # ### end Alembic commands ###
