"""empty message

Revision ID: f44ecd4f6f96
Revises: 
Create Date: 2019-08-19 16:13:35.553390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f44ecd4f6f96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timer_apply', 'apply_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True)
    op.alter_column('timer_apply', 'apply_info',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('timer_apply', 'apply_start_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='开始时间')
    op.alter_column('timer_apply', 'apply_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('timer_apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'timer_apply', 'timer_users', ['user_id'], ['user_id'])
    op.alter_column('timer_notice', 'notice_content',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    op.alter_column('timer_notice', 'notice_createTime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('timer_notice', 'notice_date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('timer_times', 'times_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('timer_times', 'times_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('timer_times', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'timer_times', 'timer_users', ['user_id'], ['user_id'])
    op.alter_column('timer_users', 'account',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True,
               comment=None,
               existing_comment='学号')
    op.alter_column('timer_users', 'grade',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('timer_users', 'sex',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.alter_column('timer_users', 'user_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('timer_users', 'user_password',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timer_users', 'user_password',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('timer_users', 'user_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('timer_users', 'sex',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    op.alter_column('timer_users', 'grade',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.alter_column('timer_users', 'account',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False,
               comment='学号')
    op.drop_constraint(None, 'timer_times', type_='foreignkey')
    op.alter_column('timer_times', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('timer_times', 'times_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('timer_times', 'times_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('timer_notice', 'notice_date',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('timer_notice', 'notice_createTime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('timer_notice', 'notice_content',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.drop_constraint(None, 'timer_apply', type_='foreignkey')
    op.alter_column('timer_apply', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('timer_apply', 'apply_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('timer_apply', 'apply_start_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='开始时间')
    op.alter_column('timer_apply', 'apply_info',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('timer_apply', 'apply_end_time',
               existing_type=mysql.DATETIME(),
               comment='结束时间',
               existing_nullable=True)
    # ### end Alembic commands ###
