"""empty message

Revision ID: fb49f49d95b6
Revises: f44ecd4f6f96
Create Date: 2019-08-19 16:34:09.740698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb49f49d95b6'
down_revision = 'f44ecd4f6f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_mac',
    sa.Column('mac_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mac', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['timer_users.user_id'], ),
    sa.PrimaryKeyConstraint('mac_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_mac')
    # ### end Alembic commands ###
